# Generated by Django 6.0.1 on 2026-01-23 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='receipe_name',
            new_name='receipce_name',
        ),
    ]
