# Generated by Django 6.0.1 on 2026-01-23 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_rename_receipe_name_receipe_receipce_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='receipce_name',
            new_name='receipe_name',
        ),
    ]
