# Generated by Django 6.0.1 on 2026-01-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_remove_receipe_receipe_discription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='user',
        ),
    ]
