# Generated by Django 6.0.1 on 2026-01-26 13:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_remove_receipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='receipe_discription',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipe',
            name='receipe_name',
            field=models.CharField(default='dahi', max_length=100),
            preserve_default=False,
        ),
    ]
