# Generated by Django 6.0.1 on 2026-01-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0007_receipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='receipe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
