# Generated by Django 6.0.1 on 2026-01-31 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0010_subject_studentmarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentMarks',
            new_name='SubjectMarks',
        ),
    ]
