# Generated by Django 6.0.1 on 2026-02-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0013_alter_reportcard_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='date_of_report_card_generation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
