# Generated by Django 6.0.1 on 2026-02-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0017_receipe_is_deleted_receipe_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
